spring.application.name=query-service
server.port=8083
spring.config.import=optional:file:./secrets.properties
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.redis.host=localhost
spring.data.redis.port=6379
openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-4o-mini
openai.base-url=https://api.openai.com/v1
openai.embedding-model=text-embedding-3-small